version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  test:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: |
            poetry run sh scripts/lint.sh
            poetry run pytest

  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Images
          command: |
            sh scripts/build.sh
            
